development:
  adapter: sqlite3
  database: db/development.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  pool: 25